#!/bin/bash

DIR_POSTS="./posts"
DIR_BIB="./tmp/bib"
DIR_HTML="./tmp/html"
DIR_XML="./tmp/xml"
DIR_STATIC="./static"
LIB="./lib"
XSL_ABOUT="$LIB/xsl/about.xsl"
XSL_ARCHIVE="$LIB/xsl/archive.xsl"
XSL_ATOM="$LIB/xsl/atom.xsl"
XSL_CSS="$LIB/xsl/css.xsl"
XSL_INDEX="$LIB/xsl/index.xsl"
XSL_POSTS="$LIB/xsl/posts.xsl"
XSL_RESUME="$LIB/xsl/resume.xsl"
XSL_CONCAT_POSTS="$LIB/xsl/concat-posts.xsl"
SAXON="$LIB/saxon/saxon-he-12.4.jar"
SCHXSLT="$LIB/schxslt/schxslt-cli.jar"
XML_CONCAT="$DIR_XML/concat/posts-concat.xml"
XML_RESUME="./xml/resume.xml"
XML_BIB="./xml/bib.xml"
FILE_BIB="./bib/bibliography.bib"
XQ_BIB="$LIB/xq/bibtex-to-xml.xq"
SCH_BLOG="$LIB/sch/blog.sch"

# TODO is cd needed?
# cd "$LIB/el"
# emacs --batch -l convert-blog-posts-to-xml.el -f convert-blog-posts-to-xml
# cd ../..
# mv $DIR_POSTS/*.xml $DIR_XML/posts

# validate
for XML_FILE in $DIR_XML/posts/*.xml; do
    java -jar $SCHXSLT -d "$XML_FILE" -s "$SCH_BLOG" -o ./report.xml
done

# convert bibtex to xml
# java -cp $SAXON net.sf.saxon.Query "$XQ_BIB" -o:"$XML_BIB"

# # TODO consolidate these
# java -cp $SAXON net.sf.saxon.Transform -t -s:"$DIR_XML/posts/2021-06-07-blog.xml" -xsl:"$XSL_CONCAT_POSTS" -o:"$XML_CONCAT"
# java -cp $SAXON net.sf.saxon.Transform -t -s:"$XML_CONCAT" -xsl:"$XSL_ATOM" -o:"$DIR_HTML/atom.xml"
# java -cp $SAXON net.sf.saxon.Transform -t -s:"$XML_CONCAT" -xsl:"$XSL_INDEX" -o:"$DIR_HTML/index.html"
# java -cp $SAXON net.sf.saxon.Transform -t -s:"$XML_CONCAT" -xsl:"$XSL_ABOUT" -o:"$DIR_HTML/about.html"
# java -cp $SAXON net.sf.saxon.Transform -t -s:"$XML_CONCAT" -xsl:"$XSL_ARCHIVE" -o:"$DIR_HTML/posts.html"
# java -cp $SAXON net.sf.saxon.Transform -t -s:"$XML_CONCAT" -xsl:"$XSL_CSS" -o:"$DIR_HTML/style.css"

# # posts
# for XML_FILE in $DIR_XML/posts/*.xml; do
#   HTML_FILE="$DIR_HTML/$(basename "$XML_FILE" .xml).html"
#   java -cp $SAXON net.sf.saxon.Transform  -t -s:"$XML_FILE" -xsl:"$XSL_POSTS" -o:"$HTML_FILE"
# done

# resume
# java -cp $SAXON net.sf.saxon.Transform  -t -s:"$XML_RESUME" -xsl:"$XSL_RESUME" -o:"$DIR_HTML/ilmari-koria-resume.tex"
# pdflatex -output-directory $DIR_HTML "$DIR_HTML/ilmari-koria-resume.tex"
# rm $DIR_HTML/*.log $DIR_HTML/*.tex $DIR_HTML/*.aux $DIR_HTML/*.out   

# # rsync -avz --delete $DIR_HTML/ root@ilmarikoria.xyz:/var/www/ilmarikoria/
# # sitemap-generator -l https://ilmarikoria.xyz
# # rsync -avz --delete sitemap.xml root@ilmarikoria.xyz:/var/www/ilmarikoria/sitemap.xml
