#!/bin/bash

DIR_POSTS="./posts"

DIR_BIB="./tmp/bib"
DIR_HTML="./tmp/html"
DIR_XML="./tmp/xml"

DIR_STATIC="./static"

LIB="./lib"

XSL_ABOUT="$LIB/xsl/about.xsl"
XSL_ARCHIVE="$LIB/xsl/archive.xsl"
XSL_ATOM="$LIB/xsl/atom.xsl"
XSL_CSS="$LIB/xsl/css.xsl"
XSL_INDEX="$LIB/xsl/index.xsl"
XSL_POSTS="$LIB/xsl/posts.xsl"
XSL_RESUME="$LIB/xsl/resume.xsl"
XSL_CONCAT_POSTS="$LIB/xsl/concat-posts.xsl"

SAXON="$LIB/saxon/saxon-he-12.4.jar"

XML_CONCAT="$DIR_XML/concat/posts-concat.xml"


cd "$LIB/el"
emacs --batch -l convert-blog-posts-to-xml.el -f convert-blog-posts-to-xml
cd ../..
mv $DIR_POSTS/*.xml $DIR_XML/posts

java -jar $SAXON -t -s:"$DIR_XML/posts/2021-06-07-blog.xml" -xsl:"$XSL_CONCAT_POSTS" -o:"$XML_CONCAT"
java -jar $SAXON -t -s:"$XML_CONCAT" -xsl:"$XSL_ATOM" -o:"$DIR_HTML/atom.xml"
java -jar $SAXON -t -s:"$XML_CONCAT" -xsl:"$XSL_INDEX" -o:"$DIR_HTML/index.html"
java -jar $SAXON -t -s:"$XML_CONCAT" -xsl:"$XSL_ABOUT" -o:"$DIR_HTML/about.html"
java -jar $SAXON -t -s:"$XML_CONCAT" -xsl:"$XSL_ARCHIVE" -o:"$HTML_DIR/posts.html"

for XML_FILE in $DIR_XML/posts/*.xml; do
  HTML_FILE="$DIR_HTML/$(basename "$XML_FILE" .xml).html"
  java -jar $SAXON -t -s:"$XML_FILE" -xsl:"$XSL_POSTS" -o:"$HTML_FILE"
done

# rsync -avz --delete $DIR_HTML/ root@ilmarikoria.xyz:/var/www/ilmarikoria/
# sitemap-generator -l https://ilmarikoria.xyz
# rsync -avz --delete sitemap.xml root@ilmarikoria.xyz:/var/www/ilmarikoria/sitemap.xml
