#!/bin/bash

ORG_DIR="../posts"
XML_DIR="../tmp/xml"
HTML_DIR="../tmp/html"
STATIC_DIR="../tmp/html/static"
IMAGES_DIR="../images"
BIB_DIR="../tmp/bib"

XSL_FILE="../xsl/stylesheet.xsl"
CSS_FILE="../css/style.css"

SAXON_JAR="../saxon/SaxonHE12-4J/saxon-he-12.4.jar"

# call om-to-xml via emacs and mv xml
emacs --batch -l ./my-convert-blog-posts-to-xml.el -f my-convert-blog-posts-to-xml
mv $ORG_DIR/*.xml $XML_DIR

# convert bib.tex to xhtml
cd $XML_DIR
bibtex2html --footer "" --header "" --no-header --nodoc --nobibsource --ignore-errors --sort-as-bibtex ../../bib/bibliography.bib
tidy -q --numeric-entities yes -asxhtml -o bibliography.xml bibliography.html
cd ../../script

# xsl call
for xml_file in $XML_DIR/*.xml; do
    if [ -f "$xml_file" ]; then
        html_file="$HTML_DIR/$(basename "$xml_file" .xml).html"
        java -jar $SAXON_JAR -t -s:"$xml_file" -xsl:"$XSL_FILE" -o:"$html_file"
    fi
done

# clean up bib files
rm $XML_DIR/bibliography.xml && rm $XML_DIR/bibliography.html && rm $HTML_DIR/bibliography.html

# html tidy
for html_file in $HTML_DIR/*.html; do
    tidy -utf8 -indent -modify $html_file        
done



# bib an style.css
cp $CSS_FILE $HTML_DIR

# create gallery
# fgallery $IMAGES_DIR $STATIC_DIR

# sync files
# rsync -avz --cvs-exclude --delete ~/my-files/blog/tmp/html/ root@ilmarikoria.xyz:/var/www/ilmarikoria/

# update sitemap
# cd $HTML_DIR
# sitemap-generator -l https://ilmarikoria.xyz
# rsync -avz --cvs-exclude --delete ~/my-files/blog/ilmarikoria/sitemap.xml root@ilmarikoria.xyz:/var/www/ilmarikoria/sitemap.xml

# cd
# echo "--"
# echo "Update website done!"

